
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int az_az_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c7,
	0x00d6,
	0x00dc,
	0x00e7,
	0x00f6,
	0x00fc,
	0x011e,
	0x011f,
	0x0130,
	0x0131,
	0x015e,
	0x015f,
	0x018f,
	0x0259,
};
#define AZ_AZ_LANG_ORTH_SZ	20
