
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int bm_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x0190,
	0x025b,
	0x014a,
	0x014b,
	0x019d,
	0x0272,
	0x0186,
	0x0254,
};
#define BM_LANG_ORTH_SZ	14
