
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int brx_lang_orth_chars[] = {
	2, 0x0901, 0x0903,	// range
	2, 0x0905, 0x090c,	// range
	2, 0x090f, 0x0910,	// range
	2, 0x0913, 0x0914,	// range
	2, 0x0915, 0x0928,	// range
	2, 0x092a, 0x0930,	// range
	2, 0x0932, 0x0932,	// range
	2, 0x0935, 0x0939,	// range
	2, 0x093c, 0x0944,	// range
	2, 0x0947, 0x0948,	// range
	2, 0x094b, 0x094d,	// range
	2, 0x0950, 0x0952,	// range
	2, 0x0960, 0x0963,	// range
	2, 0x0964, 0x0965,	// range
	2, 0x0966, 0x096f,	// range
	0x0970,
};
#define BRX_LANG_ORTH_SZ	46
