
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int chr_lang_orth_chars[] = {
	0xf0f0ffff, 0x13a0, 0x13f4,	// range
};
#define CHR_LANG_ORTH_SZ	3
