
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int chr_lang_orth_chars[] = {
	2, 0x13a0, 0x13f4,	// range
};
#define CHR_LANG_ORTH_SZ	3
