
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int dz_lang_orth_chars[] = {
	2, 0x0f40, 0x0f47,	// range
	2, 0x0f49, 0x0f69,	// range
	2, 0x0f71, 0x0f76,	// range
	0x0f78,
	2, 0x0f7a, 0x0f7d,	// range
	2, 0x0f80, 0x0f81,	// range
	2, 0x0f90, 0x0f97,	// range
	2, 0x0f99, 0x0fb9,	// range
};
#define DZ_LANG_ORTH_SZ	22
