
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int ee_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	2, 0x00c0, 0x00c1,	// range
	2, 0x00c8, 0x00c9,	// range
	2, 0x00cc, 0x00cd,	// range
	2, 0x00d2, 0x00d3,	// range
	2, 0x00d9, 0x00da,	// range
	2, 0x00e0, 0x00e1,	// range
	2, 0x00e8, 0x00e9,	// range
	2, 0x00ec, 0x00ed,	// range
	2, 0x00f2, 0x00f3,	// range
	2, 0x00f9, 0x00fa,	// range
	2, 0x011a, 0x011b,	// range
	2, 0x014a, 0x014b,	// range
	0x0186,
	0x0189,
	2, 0x0190, 0x0192,	// range
	0x0194,
	0x01b2,
	2, 0x01cd, 0x01d4,	// range
	0x0254,
	0x0256,
	0x025b,
	0x0263,
	0x028b,
	2, 0x0300, 0x0301,	// range
	0x030c,
};
#define EE_LANG_ORTH_SZ	61
