
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int eo_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0xf0f0ffff, 0x0108, 0x0109,	// range
	0xf0f0ffff, 0x011c, 0x011d,	// range
	0xf0f0ffff, 0x0124, 0x0125,	// range
	0xf0f0ffff, 0x0134, 0x0135,	// range
	0xf0f0ffff, 0x015c, 0x015d,	// range
	0xf0f0ffff, 0x016c, 0x016d,	// range
};
#define EO_LANG_ORTH_SZ	24
