
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int fo_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c1,
	0x00c6,
	0x00cd,
	0x00d0,
	0x00d3,
	0x00d8,
	0x00da,
	0x00dd,
	0x00e1,
	0x00e6,
	0x00ed,
	0x00f0,
	0x00f3,
	0x00f8,
	0x00fa,
	0x00fd,
};
#define FO_LANG_ORTH_SZ	22
