
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int gd_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c0,
	0x00c1,
	0x00c7,
	0x00c8,
	0x00c9,
	0x00cc,
	0x00d2,
	0x00d3,
	0x00d9,
	0x00e0,
	0x00e1,
	0x00e7,
	0x00e8,
	0x00e9,
	0x00ec,
	0x00f2,
	0x00f3,
	0x00f9,
};
#define GD_LANG_ORTH_SZ	24
