
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int ha_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x0181,
	0x0253,
	0x018a,
	0x0257,
	2, 0x0198, 0x0199,	// range
	0x01b3,
	0x01b4,
};
#define HA_LANG_ORTH_SZ	15
