
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int hr_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	2, 0x0106, 0x0107,	// range
	2, 0x010c, 0x010d,	// range
	2, 0x0110, 0x0111,	// range
	2, 0x0160, 0x0161,	// range
	2, 0x017d, 0x017e,	// range
};
#define HR_LANG_ORTH_SZ	21
