
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int hsb_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00d3,
	0x00f3,
	2, 0x0106, 0x0107,	// range
	2, 0x010c, 0x010d,	// range
	2, 0x011a, 0x011b,	// range
	2, 0x0141, 0x0144,	// range
	2, 0x0158, 0x0159,	// range
	2, 0x0160, 0x0161,	// range
	2, 0x0179, 0x017a,	// range
	2, 0x017d, 0x017e,	// range
};
#define HSB_LANG_ORTH_SZ	32
