
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int hu_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c1,
	0x00c9,
	0x00cd,
	0x00d3,
	0x00d6,
	0x00da,
	0x00dc,
	0x00e1,
	0x00e9,
	0x00ed,
	0x00f3,
	0x00f6,
	0x00fa,
	0x00fc,
	2, 0x0150, 0x0151,	// range
	2, 0x0170, 0x0171,	// range
};
#define HU_LANG_ORTH_SZ	26
