
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int hy_lang_orth_chars[] = {
	2, 0x0531, 0x0556,	// range
	2, 0x0561, 0x0587,	// range
};
#define HY_LANG_ORTH_SZ	6
