
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int hz_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x032f,
	2, 0x1e12, 0x1e13,	// range
	2, 0x1e4a, 0x1e4b,	// range
};
#define HZ_LANG_ORTH_SZ	13
