
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ka_lang_orth_chars[] = {
	0xf0f0ffff, 0x10d0, 0x10f0,	// range
};
#define KA_LANG_ORTH_SZ	3
