
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int kok_lang_orth_chars[] = {
	2, 0x0905, 0x0914,	// range
	2, 0x0915, 0x0939,	// range
	2, 0x093f, 0x094c,	// range
	0x094d,
};
#define KOK_LANG_ORTH_SZ	10
