
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int ku_ir_lang_orth_chars[] = {
	2, 0x0626, 0x0628,	// range
	0x062a,
	2, 0x062c, 0x062f,	// range
	2, 0x0631, 0x0634,	// range
	2, 0x0639, 0x063a,	// range
	2, 0x0641, 0x0642,	// range
	2, 0x0644, 0x0648,	// range
	0x067e,
	0x0686,
	0x0692,
	0x0698,
	0x06a4,
	0x06a9,
	0x06af,
	0x06b5,
	0x06c6,
	0x06cc,
	0x06ce,
};
#define KU_IR_LANG_ORTH_SZ	30
