
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int lv_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	2, 0x0100, 0x0101,	// range
	2, 0x010c, 0x010d,	// range
	2, 0x0112, 0x0113,	// range
	2, 0x0122, 0x0123,	// range
	2, 0x012a, 0x012b,	// range
	2, 0x0136, 0x0137,	// range
	2, 0x013b, 0x013c,	// range
	2, 0x0145, 0x0146,	// range
	2, 0x014c, 0x014d,	// range
	2, 0x0156, 0x0157,	// range
	2, 0x0160, 0x0161,	// range
	2, 0x016a, 0x016b,	// range
	2, 0x017d, 0x017e,	// range
};
#define LV_LANG_ORTH_SZ	45
