
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int mh_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x0100,
	0x0101,
	0x013b,
	0x013c,
	0x0145,
	0x0146,
	0x014c,
	0x014d,
	0x016a,
	0x016b,
};
#define MH_LANG_ORTH_SZ	16
