
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int mi_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	2, 0x0100, 0x0101,	// range
	2, 0x0112, 0x0113,	// range
	2, 0x012a, 0x012b,	// range
	2, 0x014c, 0x014d,	// range
	2, 0x016a, 0x016b,	// range
	2, 0x1e34, 0x1e35,	// range
};
#define MI_LANG_ORTH_SZ	24
