
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int mn_mn_lang_orth_chars[] = {
	0x0401,
	2, 0x0410, 0x044f,	// range
	0x0451,
	2, 0x04ae, 0x04af,	// range
	2, 0x04e8, 0x04e9,	// range
};
#define MN_MN_LANG_ORTH_SZ	11
