
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int mt_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c0,
	0x00c8,
	0x00cc,
	0x00ce,
	0x00d2,
	0x00d9,
	0x00e0,
	0x00e8,
	0x00ec,
	0x00ee,
	0x00f2,
	0x00f9,
	2, 0x010a, 0x010b,	// range
	2, 0x0120, 0x0121,	// range
	2, 0x0126, 0x0127,	// range
	2, 0x017b, 0x017c,	// range
};
#define MT_LANG_ORTH_SZ	30
