
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int na_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c3,
	0x00d1,
	0x00d5,
	0x00e3,
	0x00f1,
	0x00f5,
	2, 0x0168, 0x0169,	// range
};
#define NA_LANG_ORTH_SZ	15
