
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int nqo_lang_orth_chars[] = {
	2, 0x07c0, 0x07fa,	// range
};
#define NQO_LANG_ORTH_SZ	3
