
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int nv_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c1,
	0x00c9,
	0x00cd,
	0x00d3,
	0x00e1,
	0x00e9,
	0x00ed,
	0x00f3,
	2, 0x0104, 0x0105,	// range
	2, 0x0118, 0x0119,	// range
	2, 0x012e, 0x012f,	// range
	2, 0x0141, 0x0142,	// range
	2, 0x01ea, 0x01eb,	// range
	0x02bc,
	0x0301,
};
#define NV_LANG_ORTH_SZ	31
