
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int ota_lang_orth_chars[] = {
	2, 0x0621, 0x0622,	// range
	2, 0x0626, 0x063a,	// range
	2, 0x0641, 0x0648,	// range
	0x067e,
	0x0686,
	0x0698,
	0x06ad,
	0x06af,
	0x06cc,
};
#define OTA_LANG_ORTH_SZ	15
