
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int pap_an_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c1,
	2, 0x00c8, 0x00c9,	// range
	0x00cd,
	2, 0x00d1, 0x00d3,	// range
	2, 0x00d9, 0x00da,	// range
	0x00dc,
	0x00e1,
	2, 0x00e8, 0x00e9,	// range
	0x00ed,
	2, 0x00f1, 0x00f3,	// range
	2, 0x00f9, 0x00fa,	// range
	0x00fc,
};
#define PAP_AN_LANG_ORTH_SZ	30
