
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ps_af_lang_orth_chars[] = {
	0xf0f0ffff, 0x0621, 0x0624,	// range
	0xf0f0ffff, 0x0626, 0x063a,	// range
	0xf0f0ffff, 0x0641, 0x0642,	// range
	0xf0f0ffff, 0x0644, 0x0648,	// range
	0x064a,
	0x067c,
	0x067e,
	0x0681,
	0xf0f0ffff, 0x0685, 0x0686,	// range
	0x0689,
	0x0693,
	0x0696,
	0x0698,
	0x069a,
	0x06a9,
	0x06ab,
	0x06bc,
	0x06cc,
	0x06cd,
	0x06d0,
};
#define PS_AF_LANG_ORTH_SZ	30
