
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int ro_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c2,
	0x00ce,
	0x00e2,
	0x00ee,
	2, 0x0102, 0x0103,	// range
	2, 0x0218, 0x021b,	// range
};
#define RO_LANG_ORTH_SZ	16
