
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int sms_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c2,
	0x00e2,
	0x00c4,
	0x00e4,
	0x00c5,
	0x00e5,
	2, 0x010c, 0x010d,	// range
	2, 0x0110, 0x0111,	// range
	0x01b7,
	0x0292,
	2, 0x01ee, 0x01ef,	// range
	2, 0x01e6, 0x01e7,	// range
	2, 0x01e4, 0x01e5,	// range
	2, 0x01e8, 0x01e9,	// range
	2, 0x014a, 0x014b,	// range
	0x00d5,
	0x00f5,
	2, 0x0160, 0x0161,	// range
	2, 0x017d, 0x017e,	// range
};
#define SMS_LANG_ORTH_SZ	43
