
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int sr_lang_orth_chars[] = {
	0x0402,
	2, 0x0408, 0x040b,	// range
	0x040f,
	2, 0x0410, 0x0418,	// range
	2, 0x041a, 0x0428,	// range
	2, 0x0430, 0x0438,	// range
	2, 0x043a, 0x0448,	// range
	0x0452,
	2, 0x0458, 0x045b,	// range
	0x045f,
};
#define SR_LANG_ORTH_SZ	22
