
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int syr_lang_orth_chars[] = {
	2, 0x0710, 0x072c,	// range
	2, 0x0730, 0x073f,	// range
};
#define SYR_LANG_ORTH_SZ	6
