
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int th_lang_orth_chars[] = {
	2, 0x0e01, 0x0e3a,	// range
	2, 0x0e3f, 0x0e4e,	// range
};
#define TH_LANG_ORTH_SZ	6
