
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int tk_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c4,
	0x00c7,
	0x00d6,
	2, 0x00dc, 0x00dd,	// range
	0x00e4,
	0x00e7,
	0x00f6,
	2, 0x00fc, 0x00fd,	// range
	2, 0x0147, 0x0148,	// range
	2, 0x015e, 0x015f,	// range
	2, 0x017d, 0x017e,	// range
};
#define TK_LANG_ORTH_SZ	27
