
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int vot_lang_orth_chars[] = {
	2, 0x0041, 0x005a,	// range
	2, 0x0061, 0x007a,	// range
	0x00c4,
	0x00d6,
	0x00dc,
	0x00e4,
	0x00f6,
	0x00fc,
	2, 0x0160, 0x0161,	// range
	2, 0x017d, 0x017e,	// range
};
#define VOT_LANG_ORTH_SZ	18
