
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by fc-lang_conv at https://github.com/virxkane/freetype_textdraw

unsigned int yi_lang_orth_chars[] = {
	2, 0x05d0, 0x05ea,	// range
};
#define YI_LANG_ORTH_SZ	3
