call makedocs.bat
del cr3-src.zip
7z a -tzip cr3-src.zip aclocal.m4
7z a -tzip cr3-src.zip authors
7z a -tzip cr3-src.zip changelog
7z a -tzip cr3-src.zip config.guess
7z a -tzip cr3-src.zip config.sub
7z a -tzip cr3-src.zip configure
7z a -tzip cr3-src.zip configure.in
7z a -tzip cr3-src.zip copying
7z a -tzip cr3-src.zip cr3.kdevelop
7z a -tzip cr3-src.zip depcomp
7z a -tzip cr3-src.zip doxyfile
7z a -tzip cr3-src.zip install
7z a -tzip cr3-src.zip install-sh
7z a -tzip cr3-src.zip ltmain.sh
7z a -tzip cr3-src.zip makefile.am
7z a -tzip cr3-src.zip makefile.cvs
7z a -tzip cr3-src.zip makefile.in
7z a -tzip cr3-src.zip missing
7z a -tzip cr3-src.zip mksrcdst.bat
7z a -tzip cr3-src.zip news
7z a -tzip cr3-src.zip readme
7z a -tzip cr3-src.zip todo
7z a -tzip cr3-src.zip templates\*
7z a -tzip cr3-src.zip macros\*.*
7z a -tzip cr3-src.zip src\cr3.cpp
7z a -tzip cr3-src.zip src\cr3.desktop
7z a -tzip cr3-src.zip src\cr3.dsp
7z a -tzip cr3-src.zip src\cr3.dsw
7z a -tzip cr3-src.zip src\cr3.h
7z a -tzip cr3-src.zip src\cr3.ico
7z a -tzip cr3-src.zip src\cr3.rc
7z a -tzip cr3-src.zip src\cr3.xpm
7z a -tzip cr3-src.zip src\hi16-app-cr3.png
7z a -tzip cr3-src.zip src\hi32-app-cr3.png
7z a -tzip cr3-src.zip src\makefile.am
7z a -tzip cr3-src.zip src\makefile.in
7z a -tzip cr3-src.zip src\resource.h
7z a -tzip cr3-src.zip src\stdafx.cpp
7z a -tzip cr3-src.zip src\stdafx.h
7z a -tzip cr3-src.zip src\resources\cr3res.h
7z a -tzip cr3-src.zip src\resources\cr3res.zip
7z a -tzip cr3-src.zip src\resources\crrcconv.cpp
7z a -tzip cr3-src.zip src\resources\makeres

