// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int as_lang_orth_chars[] = {
//
// fontconfig/fc-lang/as.orth
//
// Copyright © 2006 Keith Packard
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Assamese (as)
//
// Source: Unicode coverage and notes for Bengali script, Unicode internal
// documents, Wikipedia articles
	0xf0f0ffff, 0x0981, 0x0983,	// range
	0xf0f0ffff, 0x0985, 0x098c,	// range
	0xf0f0ffff, 0x098f, 0x0990,	// range
	0xf0f0ffff, 0x0993, 0x09a8,	// range
	0xf0f0ffff, 0x09aa, 0x09af,	// range
// 09b0 // Assamese uses U+09F0 instead
	0x09b2,
	0xf0f0ffff, 0x09b6, 0x09b9,	// range
	0x09bc,
	0xf0f0ffff, 0x09be, 0x09c4,	// range
	0xf0f0ffff, 0x09c7, 0x09c8,	// range
	0xf0f0ffff, 0x09cb, 0x09cd,	// range
// 09d7 // Only used as a part of U+09CC
	0xf0f0ffff, 0x09dc, 0x09dd,	// range
	0x09df,
// 09e0-09e3 // These are for Sanskrit
	0xf0f0ffff, 0x09f0, 0x09f1,	// range
};
#define AS_LANG_ORTH_SZ	36

// clang-format on
