// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ba_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ba.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Bashkir (BA)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
//00AA	// FEMININE ORDINAL INDICATOR
//00BB	// RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK *
//0401	// CYRILLIC CAPITAL LETTER IO	in evertype.com
//0451	// CYRILLIC SMALL LETTER IO	in evertype.com
	0xf0f0ffff, 0x0410, 0x044f,	// range	// CYRILLIC
	0x0492,	// CYRILLIC CAPITAL LETTER GHE WITH STROKE
	0x0493,	// CYRILLIC SMALL LETTER GHE WITH STROKE
	0x0498,	// CYRILLIC CAPITAL LETTER ZE WITH DESCENDER
	0x0499,	// CYRILLIC SMALL LETTER ZE WITH DESCENDER
	0x04a0,	// CYRILLIC CAPITAL LETTER BASHKIR KA
	0x04a1,	// CYRILLIC SMALL LETTER BASHKIR KA
	0x04a2,	// CYRILLIC CAPITAL LETTER EN WITH DESCENDER
	0x04a3,	// CYRILLIC SMALL LETTER EN WITH DESCENDER
	0x04aa,	// CYRILLIC CAPITAL LETTER ES WITH DESCENDER
	0x04ab,	// CYRILLIC SMALL LETTER ES WITH DESCENDER
	0x04ae,	// CYRILLIC CAPITAL LETTER STRAIGHT U
	0x04af,	// CYRILLIC SMALL LETTER STRAIGHT U
	0x04ba,	// CYRILLIC CAPITAL LETTER SHHA
	0x04bb,	// CYRILLIC SMALL LETTER SHHA
	0x04d8,	// CYRILLIC CAPITAL LETTER SCHWA
	0x04d9,	// CYRILLIC SMALL LETTER SCHWA
	0x04e8,	// CYRILLIC CAPITAL LETTER BARRED O
	0x04e9,	// CYRILLIC SMALL LETTER BARRED O
//2018-2019	// single quotes
//201c-201d	// double quotes
//2039-203a	// angle quotes
};
#define BA_LANG_ORTH_SZ	21

// clang-format on
