// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ber_ma_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ber_ma.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Berber in Morocco (ber-MA)
//
// Tifinagh is the official script for Berber language(s) in Morocco.
// The character list comes from Institut Royal de la Culture Amazighe (IRCAM).
// Sources:
// http://www.omniglot.com/writing/tifinagh.htm
// http://www.win.tue.nl/~aeb/natlang/berber/tifinagh/tifinagh.html
	0xf0f0ffff, 0x2d30, 0x2d31,	// range
	0x2d33,
	0x2d37,
	0x2d39,
	0xf0f0ffff, 0x2d3b, 0x2d3d,	// range
	0x2d40,
	0xf0f0ffff, 0x2d43, 0x2d45,	// range
	0x2d47,
	0xf0f0ffff, 0x2d49, 0x2d4a,	// range
	0xf0f0ffff, 0x2d4d, 0x2d4f,	// range
	0xf0f0ffff, 0x2d53, 0x2d56,	// range
	0xf0f0ffff, 0x2d59, 0x2d5c,	// range
	0x2d5f,
	0xf0f0ffff, 0x2d61, 0x2d63,	// range
	0x2d65,
	0x2d6f,
};
#define BER_MA_LANG_ORTH_SZ	32

// clang-format on
