// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int bo_lang_orth_chars[] = {
//
// fontconfig/fc-lang/bo.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Tibetan (BO)
//
// Taken from the Unicode coverage of this language
//
	0xf0f0ffff, 0x0f40, 0x0f47,	// range
	0xf0f0ffff, 0x0f49, 0x0f69,	// range
	0xf0f0ffff, 0x0f71, 0x0f76,	// range
	0x0f78,
	0xf0f0ffff, 0x0f7a, 0x0f7d,	// range
	0xf0f0ffff, 0x0f80, 0x0f81,	// range
	0xf0f0ffff, 0x0f90, 0x0f97,	// range
	0xf0f0ffff, 0x0f99, 0x0fb9,	// range
// Fixed-form subjoined consonants
// These characters are used only for transliteration and transcription.
//0fba-0fbc
};
#define BO_LANG_ORTH_SZ	22

// clang-format on
