// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int br_lang_orth_chars[] = {
//
// fontconfig/fc-lang/br.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Breton (BR)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
//0027
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
//00AB		// LEFT-POINTING DOUBLE ANGLE QUOTATION MARK *
//00BB		// RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK *
	0x00c2,		// LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	0x00ca,		// LATIN CAPITAL LETTER E WITH CIRCUMFLEX
	0x00d1,		// LATIN CAPITAL LETTER N WITH TILDE
	0x00d4,		// LATIN CAPITAL LETTER O WITH CIRCUMFLEX	eki.ee
	0x00d9,		// LATIN CAPITAL LETTER U WITH GRAVE
	0x00dc,		// LATIN CAPITAL LETTER U WITH DIAERESIS
	0x00e2,		// LATIN SMALL LETTER A WITH CIRCUMFLEX
	0x00ea,		// LATIN SMALL LETTER E WITH CIRCUMFLEX
	0x00f1,		// LATIN SMALL LETTER N WITH TILDE
	0x00f4,		// LATIN SMALL LETTER O WITH CIRCUMFLEX		eki.ee
	0x00f9,		// LATIN SMALL LETTER U WITH GRAVE
	0x00fc,		// LATIN SMALL LETTER U WITH DIAERESIS
//2019-201a	// single quote and comma
};
#define BR_LANG_ORTH_SZ	18

// clang-format on
