// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int crh_lang_orth_chars[] = {
//
// fontconfig/fc-lang/crh.orth
//
// Copyright © 2009 Roozbeh Pournader
// Copyright © 2009 Reşat SABIQ
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Crimean Tatar/Crimean Turkish (crh)
//
// Sources:
// * http://www.omniglot.com/writing/crimeantatar.php
// * http://en.wikipedia.org/wiki/Crimean_Tatar_language
// * http://www.vatankirim.net/yazi.asp?yaziNo=31
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c2,
	0x00c7,
	0x00d1,
	0x00d6,
	0x00dc,
	0x00e2,
	0x00e7,
	0x00f1,
	0x00f6,
	0x00fc,
	0xf0f0ffff, 0x011e, 0x011f,	// range
	0xf0f0ffff, 0x0130, 0x0131,	// range
	0xf0f0ffff, 0x015e, 0x015f,	// range
};
#define CRH_LANG_ORTH_SZ	25

// clang-format on
