// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int cs_lang_orth_chars[] = {
//
// fontconfig/fc-lang/cs.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Czech (CS)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c1,		// LATIN CAPITAL LETTER A WITH ACUTE
//00C4		// LATIN CAPITAL LETTER A WITH DIAERESIS		evertype.com
	0x00c9,		// LATIN CAPITAL LETTER E WITH ACUTE
	0x00cd,		// LATIN CAPITAL LETTER I WITH ACUTE
	0x00d3,		// LATIN CAPITAL LETTER O WITH ACUTE
//00D6		// LATIN CAPITAL LETTER O WITH DIAERESIS		evertype.com
	0x00da,		// LATIN CAPITAL LETTER U WITH ACUTE
//00DC		// LATIN CAPITAL LETTER U WITH DIAERESIS		evertype.com
	0x00dd,		// LATIN CAPITAL LETTER Y WITH ACUTE
	0x00e1,		// LATIN SMALL LETTER A WITH ACUTE
//00E4		// LATIN SMALL LETTER A WITH DIAERESIS		evertype.com
	0x00e9,		// LATIN SMALL LETTER E WITH ACUTE
	0x00ed,		// LATIN SMALL LETTER I WITH ACUTE
	0x00f3,		// LATIN SMALL LETTER O WITH ACUTE
//00F6		// LATIN SMALL LETTER O WITH DIAERESIS		evertype.com
	0x00fa,		// LATIN SMALL LETTER U WITH ACUTE
//00FC		// LATIN SMALL LETTER U WITH DIAERESIS		evertype.com
	0x00fd,		// LATIN SMALL LETTER Y WITH ACUTE
	0x010c,		// LATIN CAPITAL LETTER C WITH CARON
	0x010d,		// LATIN SMALL LETTER C WITH CARON
	0x010e,		// LATIN CAPITAL LETTER D WITH CARON
	0x010f,		// LATIN SMALL LETTER D WITH CARON
	0x011a,		// LATIN CAPITAL LETTER E WITH CARON
	0x011b,		// LATIN SMALL LETTER E WITH CARON
	0x0147,		// LATIN CAPITAL LETTER N WITH CARON
	0x0148,		// LATIN SMALL LETTER N WITH CARON
	0x0158,		// LATIN CAPITAL LETTER R WITH CARON
	0x0159,		// LATIN SMALL LETTER R WITH CARON
	0x0160,		// LATIN CAPITAL LETTER S WITH CARON
	0x0161,		// LATIN SMALL LETTER S WITH CARON
	0x0164,		// LATIN CAPITAL LETTER T WITH CARON
	0x0165,		// LATIN SMALL LETTER T WITH CARON
	0x016e,		// LATIN CAPITAL LETTER U WITH RING ABOVE
	0x016f,		// LATIN SMALL LETTER U WITH RING ABOVE
	0x017d,		// LATIN CAPITAL LETTER Z WITH CARON
	0x017e,		// LATIN SMALL LETTER Z WITH CARON
};
#define CS_LANG_ORTH_SZ	36

// clang-format on
