// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ee_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ee.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Ewe (ee)
//
// Sources:
// * http://www.uni-koeln.de/phil-fak/afrikanistik/down/publikationen/basic_ewe.pdf
// * http://en.wikipedia.org/wiki/Ewe_language
// * http://www.omniglot.com/writing/ewe.htm
// * http://www.panafril10n.org/wikidoc/pmwiki.php/PanAfrLoc/Gbe
//
// We amend the main alphabet with tone marks over each vowel, but some
// combinations lack precomposed forms in Unicode, so we also add individual
// combining marks.
//
// Sources also differ on the notation used for the fourth tone: circumflex
// vs combining line above (U+030D). At the moment, we are not including any
// of the two.
//
// There is also a nasalization mark for vowels (combining tilde), but there
// is a need for more research to find which vowels it's used with. The
// combination of nasalization and tones may also exist, resulting in double
// accents.
//
// C, J, and Q are not used.
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0xf0f0ffff, 0x00c0, 0x00c1,	// range
	0xf0f0ffff, 0x00c8, 0x00c9,	// range
	0xf0f0ffff, 0x00cc, 0x00cd,	// range
	0xf0f0ffff, 0x00d2, 0x00d3,	// range
	0xf0f0ffff, 0x00d9, 0x00da,	// range
	0xf0f0ffff, 0x00e0, 0x00e1,	// range
	0xf0f0ffff, 0x00e8, 0x00e9,	// range
	0xf0f0ffff, 0x00ec, 0x00ed,	// range
	0xf0f0ffff, 0x00f2, 0x00f3,	// range
	0xf0f0ffff, 0x00f9, 0x00fa,	// range
	0xf0f0ffff, 0x011a, 0x011b,	// range
	0xf0f0ffff, 0x014a, 0x014b,	// range
	0x0186,
	0x0189,
// 018A // according to Unicode characters notes for U+0257
	0xf0f0ffff, 0x0190, 0x0192,	// range
	0x0194,
	0x01b2,
	0xf0f0ffff, 0x01cd, 0x01d4,	// range
	0x0254,
	0x0256,
// 0257 // according to Unicode character notes
	0x025b,
	0x0263,
	0x028b,
	0xf0f0ffff, 0x0300, 0x0301,	// range // to be used with open e and open o
// 0303 // combining tilde
	0x030c, // to be used with open e and open o
// 030D // combining vertical line above
};
#define EE_LANG_ORTH_SZ	61

// clang-format on
