
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ff_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x0181,
	0x0253,
	0x018a,
	0x0257,
	0x014a,
	0x014b,
	0x019d,
	0x0272,
	0xf0f0ffff, 0x01b3, 0x01b4,	// range
};
#define FF_LANG_ORTH_SZ	17
