// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int fi_lang_orth_chars[] = {
//
// fontconfig/fc-lang/fi.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Finnish (FI)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
//00BB		// RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK *
	0x00c4,		// LATIN CAPITAL LETTER A WITH DIAERESIS
	0x00c5,		// LATIN CAPITAL LETTER A WITH RING ABOVE
//00C6		// LATIN CAPITAL LETTER AE (ash) *		evertype.com
//00D5		// LATIN CAPITAL LETTER O WITH TILDE		evertype.com
	0x00d6,		// LATIN CAPITAL LETTER O WITH DIAERESIS
//00DC		// LATIN CAPITAL LETTER U WITH DIAERESIS		evertype.com
	0x00e4,		// LATIN SMALL LETTER A WITH DIAERESIS
	0x00e5,		// LATIN SMALL LETTER A WITH RING ABOVE
//00E6		// LATIN SMALL LETTER AE (ash) *			evertype.com
//00F5		// LATIN SMALL LETTER O WITH TILDE		evertype.com
	0x00f6,		// LATIN SMALL LETTER O WITH DIAERESIS
//00FC		// LATIN SMALL LETTER U WITH DIAERESIS		evertype.com
	0x0160,		// LATIN CAPITAL LETTER S WITH CARON
	0x0161,		// LATIN SMALL LETTER S WITH CARON
	0x017d,		// LATIN CAPITAL LETTER Z WITH CARON
	0x017e,		// LATIN SMALL LETTER Z WITH CARON
//2019		// single quote
//201d		// double quote
//203a		// angle quote
};
#define FI_LANG_ORTH_SZ	16

// clang-format on
