// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int gez_lang_orth_chars[] = {
//
// fontconfig/fc-lang/gez.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Ethiopic (Geez) (eth)
//
// Taken from Unicode coverage (1200-137f)
//
// Sylables
	0xf0f0ffff, 0x1200, 0x1206,	// range  // he-ho
	0xf0f0ffff, 0x1208, 0x1216,	// range  // le-Ho,  skip HWa
	0xf0f0ffff, 0x1218, 0x1226,	// range  // me-`so, skip `sWa
	0xf0f0ffff, 0x1228, 0x1230,	// range  // re-sWa
	0xf0f0ffff, 0x1238, 0x1246,	// range  // re-qo
	0x1248,       // qWe
	0xf0f0ffff, 0x124a, 0x124d,	// range  // qWi-qW
	0xf0f0ffff, 0x1260, 0x1267,	// range  // be-bWa
	0xf0f0ffff, 0x1270, 0x1277,	// range  // te-to
	0xf0f0ffff, 0x1280, 0x1286,	// range  // `he-`ho
	0x1288,       // hWe
	0xf0f0ffff, 0x128a, 0x128d,	// range  // hWi-hW
	0xf0f0ffff, 0x1290, 0x1297,	// range  // ne-nWa
	0xf0f0ffff, 0x12a0, 0x12a7,	// range  // a-o, skip ea
	0xf0f0ffff, 0x12a8, 0x12ae,	// range  // ke-ko
	0x12b0,       // kWe
	0xf0f0ffff, 0x12b2, 0x12b5,	// range  // kWi-kW
	0xf0f0ffff, 0x12c8, 0x12ce,	// range  // we-wo
	0xf0f0ffff, 0x12d0, 0x12d6,	// range  // `e-`o
	0xf0f0ffff, 0x12d8, 0x12df,	// range  // ze-zWa
	0xf0f0ffff, 0x12e8, 0x12ee,	// range  // ye-yo
	0xf0f0ffff, 0x12f0, 0x12f7,	// range  // de-dWa
	0xf0f0ffff, 0x1308, 0x130e,	// range  // ge-go
	0x1310,       // gWe
	0xf0f0ffff, 0x1312, 0x1315,	// range  // gWi-gW
	0xf0f0ffff, 0x1320, 0x1328,	// range  // Te-TWa
	0xf0f0ffff, 0x1330, 0x1346,	// range  // Pe-`So
	0xf0f0ffff, 0x1348, 0x1356,	// range  // fe-po, skip pWa, rYa, mYa, fYa
//1361-1368	// punctuation
//1369-1371	// digits
//1372-137c	// numbers
//
};
#define GEZ_LANG_ORTH_SZ	76

// clang-format on
