// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int gu_lang_orth_chars[] = {
//
// fontconfig/fc-lang/gu.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Gujarati (gu)
//
// Taken from the Unicode coverage of this language
//
	0xf0f0ffff, 0x0a81, 0x0a83,	// range
	0xf0f0ffff, 0x0a85, 0x0a8b,	// range
	0x0a8d,
	0xf0f0ffff, 0x0a8f, 0x0a91,	// range
	0xf0f0ffff, 0x0a93, 0x0aa8,	// range
	0xf0f0ffff, 0x0aaa, 0x0ab0,	// range
	0xf0f0ffff, 0x0ab2, 0x0ab3,	// range
	0xf0f0ffff, 0x0ab5, 0x0ab9,	// range
	0xf0f0ffff, 0x0abc, 0x0ac5,	// range
	0xf0f0ffff, 0x0ac7, 0x0ac9,	// range
	0xf0f0ffff, 0x0acb, 0x0acd,	// range
	0x0ad0,
	0x0ae0,
//0ae6-0aef // Digits
};
#define GU_LANG_ORTH_SZ	33

// clang-format on
