// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int hne_lang_orth_chars[] = {
//
// fontconfig/fc-lang/hne.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Chhattisgarhi (hne)
//
// The government of India considers this a dialect of Hindi:
// including Hindi until further information is found.
//
// fontconfig/fc-lang/hi.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Hindi (Devanagari script) (HI)
//
// From Unicode coverage for Devanagari
//
	0xf0f0ffff, 0x0905, 0x0914,	// range	// Independent vowels
	0xf0f0ffff, 0x0915, 0x0939,	// range	// Consonants
	0xf0f0ffff, 0x093f, 0x094c,	// range	// Dependent vowel signs
	0x094d,		// virama
//0958-095f	// Additional consonants
//0960-0965	// Generic additions
//0966-096f	// Digits
//0970		// Abbreviation sign
};
#define HNE_LANG_ORTH_SZ	10

// clang-format on
