
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int hy_lang_orth_chars[] = {
	0xf0f0ffff, 0x0531, 0x0556,	// range
	0xf0f0ffff, 0x0561, 0x0587,	// range
};
#define HY_LANG_ORTH_SZ	6
