// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int is_lang_orth_chars[] = {
//
// fontconfig/fc-lang/is.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Icelandic (IS)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c1,
//00C4		// LATIN CAPITAL LETTER A WITH DIAERESIS		evertype.com
//00C5		// LATIN CAPITAL LETTER A WITH RING ABOVE	evertype.com
	0x00c6,
	0x00c9,
//00CB		// LATIN CAPITAL LETTER E WITH DIAERESIS		evertype.com
	0x00cd,
	0x00d0,
	0x00d3,
//00D6		// LATIN CAPITAL LETTER O WITH DIAERESIS		eki.ee
//00D8		// LATIN CAPITAL LETTER O WITH STROKE		evertype.com
	0x00da,
//00DC		// LATIN CAPITAL LETTER U WITH DIAERESIS		evertype.com
	0x00dd,
	0x00de,
	0x00e1,
//00E4		// LATIN SMALL LETTER A WITH DIAERESIS		evertype.com
//00E5		// LATIN SMALL LETTER A WITH RING ABOVE		evertype.com
	0x00e6,
	0x00e9,
	0x00ed,
	0x00f0,
	0x00f3,
//00F6		// LATIN SMALL LETTER O WITH DIAERESIS		eki.ee
//00F8		// LATIN SMALL LETTER O WITH STROKE		evertype.com
	0x00fa,
//00FC		// LATIN SMALL LETTER U WITH DIAERESIS		evertype.com
	0x00fd,
	0x00fe,
//2018	// single quote
//201a	// single quote
//201c	// double quote
//201e	// double quote
};
#define IS_LANG_ORTH_SZ	24

// clang-format on
