// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int kk_lang_orth_chars[] = {
//
// fontconfig/fc-lang/kk.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Kazakh (KK)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
//00ab
//00bb
//0401
//0406
	0xf0f0ffff, 0x0410, 0x044f,	// range
//0451
	0x0456,
	0xf0f0ffff, 0x0492, 0x0493,	// range
	0xf0f0ffff, 0x049a, 0x049b,	// range
	0xf0f0ffff, 0x04a2, 0x04a3,	// range
//04ae-04af
//04b0-04b1
	0xf0f0ffff, 0x04ba, 0x04bb,	// range
	0xf0f0ffff, 0x04d8, 0x04d9,	// range
	0xf0f0ffff, 0x04e8, 0x04e9,	// range
//2039-203a	// angle quotes
};
#define KK_LANG_ORTH_SZ	22

// clang-format on
