// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int kl_lang_orth_chars[] = {
//
// fontconfig/fc-lang/kl.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Greenlandic (KL)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
//00ab
//00bb
	0x00c1,
	0x00c2,
	0x00c3,
	0x00c5,
	0x00c6,
//00c9
	0x00ca,
	0x00cd,
	0x00ce,
	0x00d4,
	0x00d8,
	0x00da,
	0x00db,
	0x00e1,
	0x00e2,
	0x00e3,
	0x00e5,
	0x00e6,
//00e9
	0x00ea,
	0x00ed,
	0x00ee,
	0x00f4,
	0x00f8,
	0x00fa,
	0x00fb,
	0xf0f0ffff, 0x0128, 0x0129,	// range
	0x0138,
	0xf0f0ffff, 0x0168, 0x0169,	// range
//2039-203a	// angle quotes
};
#define KL_LANG_ORTH_SZ	37

// clang-format on
