// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ku_ir_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ku_ir.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Kurdish in Iran (KU-IR)
//
// Data from Roozbeh Pournader <roozbeh@sharif.edu>
//
// Since the Unicode Presentation Forms don't contain some of the Kurdish
// letters, we are going with the general forms instead of the Presentation
// forms, unlike Arabic, Persian, or Urdu.
//
	0xf0f0ffff, 0x0626, 0x0628,	// range
	0x062a,
	0xf0f0ffff, 0x062c, 0x062f,	// range
	0xf0f0ffff, 0x0631, 0x0634,	// range
	0xf0f0ffff, 0x0639, 0x063a,	// range
	0xf0f0ffff, 0x0641, 0x0642,	// range
	0xf0f0ffff, 0x0644, 0x0648,	// range
	0x067e,
	0x0686,
	0x0692,
	0x0698,
	0x06a4,
	0x06a9,
	0x06af,
	0x06b5,
	0x06c6,
	0x06cc,
	0x06ce,
};
#define KU_IR_LANG_ORTH_SZ	30

// clang-format on
