// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ln_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ln.orth
//
// Copyright © 2006 Danis Jacquerye
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Lingala (LN)
	0xf0f0ffff, 0x0041, 0x005a,	// range	// r used in borrowed words, x and q unused.
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0xf0f0ffff, 0x00c1, 0x00c2,	// range	// tonal orthography
	0xf0f0ffff, 0x00c9, 0x00ca,	// range
	0xf0f0ffff, 0x00cd, 0x00ce,	// range
	0xf0f0ffff, 0x00d3, 0x00d4,	// range
	0xf0f0ffff, 0x00da, 0x00db,	// range
	0xf0f0ffff, 0x00e1, 0x00e2,	// range
	0xf0f0ffff, 0x00e9, 0x00ea,	// range
	0xf0f0ffff, 0x00ed, 0x00ee,	// range
	0xf0f0ffff, 0x00f3, 0x00f4,	// range
	0xf0f0ffff, 0x00fa, 0x00fb,	// range
	0xf0f0ffff, 0x011a, 0x011b,	// range
	0x0186,
	0x0190,
	0x0254,
	0x025b,
	0xf0f0ffff, 0x0301, 0x0302,	// range	// combining diacritics for accented 0186, 0190, 0254, 025b
	0x030c,
};
#define LN_LANG_ORTH_SZ	47

// clang-format on
