// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int lo_lang_orth_chars[] = {
//
// fontconfig/fc-lang/lo.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Lao (lo)
//
// Taken from the Unicode coverage of this language
//
	0xf0f0ffff, 0x0e81, 0x0e82,	// range
	0x0e84,
	0xf0f0ffff, 0x0e87, 0x0e88,	// range
	0x0e8a,
	0x0e8d,
	0xf0f0ffff, 0x0e94, 0x0e97,	// range
	0xf0f0ffff, 0x0e99, 0x0e9f,	// range
	0xf0f0ffff, 0x0ea1, 0x0ea3,	// range
	0x0ea5,
	0x0ea7,
	0xf0f0ffff, 0x0eaa, 0x0eab,	// range
	0xf0f0ffff, 0x0ead, 0x0eb9,	// range
	0xf0f0ffff, 0x0ebb, 0x0ebd,	// range
	0xf0f0ffff, 0x0ec0, 0x0ec4,	// range
	0x0ec6,
	0xf0f0ffff, 0x0ec8, 0x0ecd,	// range
//0ed0-0ed9 // Digits
	0xf0f0ffff, 0x0edc, 0x0edd,	// range
};
#define LO_LANG_ORTH_SZ	39

// clang-format on
