// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int lv_lang_orth_chars[] = {
//
// fontconfig/fc-lang/lv.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Latvian (LV)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0xf0f0ffff, 0x0100, 0x0101,	// range
	0xf0f0ffff, 0x010c, 0x010d,	// range
	0xf0f0ffff, 0x0112, 0x0113,	// range
	0xf0f0ffff, 0x0122, 0x0123,	// range
	0xf0f0ffff, 0x012a, 0x012b,	// range
	0xf0f0ffff, 0x0136, 0x0137,	// range
	0xf0f0ffff, 0x013b, 0x013c,	// range
	0xf0f0ffff, 0x0145, 0x0146,	// range
	0xf0f0ffff, 0x014c, 0x014d,	// range
	0xf0f0ffff, 0x0156, 0x0157,	// range
	0xf0f0ffff, 0x0160, 0x0161,	// range
	0xf0f0ffff, 0x016a, 0x016b,	// range
	0xf0f0ffff, 0x017d, 0x017e,	// range
};
#define LV_LANG_ORTH_SZ	45

// clang-format on
