// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int mn_cn_lang_orth_chars[] = {
//
// fontconfig/fc-lang/mn_cn.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Mongolian in China (mn-CN)
//
// Taken from the Unicode coverage of this language
//
// Basic letters
	0xf0f0ffff, 0x1820, 0x1842,	// range
// Todo letters
	0xf0f0ffff, 0x1843, 0x185c,	// range
// Sibe letters
	0xf0f0ffff, 0x185d, 0x1872,	// range
// Manchu letters
	0xf0f0ffff, 0x1873, 0x1877,	// range
// Extensions for Sanskrit and Tibetan
	0xf0f0ffff, 0x1880, 0x18a9,	// range
};
#define MN_CN_LANG_ORTH_SZ	15

// clang-format on
