
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int mo_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c2,
	0x00ce,
	0x00e2,
	0x00ee,
	0xf0f0ffff, 0x0102, 0x0103,	// range
	0xf0f0ffff, 0x0218, 0x021b,	// range
	0x0401,
	0xf0f0ffff, 0x0410, 0x044f,	// range
	0x0451,
};
#define MO_LANG_ORTH_SZ	21
