// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int nn_lang_orth_chars[] = {
//
// fontconfig/fc-lang/nn.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Norwegian Nynorsk (NN)
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
//00ab		// double angle quotes
//00bb		// double angle quotes
	0x00c0,
	0xf0f0ffff, 0x00c4, 0x00c6,	// range
	0xf0f0ffff, 0x00c9, 0x00ca,	// range
	0xf0f0ffff, 0x00d2, 0x00d4,	// range
	0x00d6,
	0x00d8,
	0x00dc,
	0x00e0,
	0xf0f0ffff, 0x00e4, 0x00e6,	// range
	0xf0f0ffff, 0x00e9, 0x00ea,	// range
	0xf0f0ffff, 0x00f2, 0x00f4,	// range
	0x00f6,
	0x00f8,
	0x00fc,
//2039-203a	// single quotes
};
#define NN_LANG_ORTH_SZ	32

// clang-format on
