// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int nv_lang_orth_chars[] = {
//
// fontconfig/fc-lang/nv.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Navajo/Navaho (nv)
//
// Sources:
// * http://en.wikipedia.org/wiki/Navajo_language
// * http://www.omniglot.com/writing/navajo.htm
//
// F, P, Q, R, U, and V are not used.  A vertical glottal stop may be used.
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c1,
	0x00c9,
	0x00cd,
	0x00d3,
	0x00e1,
	0x00e9,
	0x00ed,
	0x00f3,
	0xf0f0ffff, 0x0104, 0x0105,	// range
	0xf0f0ffff, 0x0118, 0x0119,	// range
	0xf0f0ffff, 0x012e, 0x012f,	// range
	0xf0f0ffff, 0x0141, 0x0142,	// range
	0xf0f0ffff, 0x01ea, 0x01eb,	// range
	0x02bc, // modifier letter apostrophe
	0x0301, // combining acute accent, to be used with ogonek-ed forms of vowels
};
#define NV_LANG_ORTH_SZ	31

// clang-format on
