// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int or_lang_orth_chars[] = {
//
// fontconfig/fc-lang/or.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Oriya (or)
//
// Taken from the Unicode coverage of this language
//
	0xf0f0ffff, 0x0b01, 0x0b03,	// range
	0xf0f0ffff, 0x0b05, 0x0b0c,	// range
	0xf0f0ffff, 0x0b0f, 0x0b10,	// range
	0xf0f0ffff, 0x0b13, 0x0b28,	// range
	0xf0f0ffff, 0x0b2a, 0x0b30,	// range
	0xf0f0ffff, 0x0b32, 0x0b33,	// range
	0xf0f0ffff, 0x0b36, 0x0b39,	// range
	0xf0f0ffff, 0x0b3c, 0x0b43,	// range
	0xf0f0ffff, 0x0b47, 0x0b48,	// range
	0xf0f0ffff, 0x0b4b, 0x0b4d,	// range
	0xf0f0ffff, 0x0b56, 0x0b57,	// range
	0xf0f0ffff, 0x0b5c, 0x0b5d,	// range
	0xf0f0ffff, 0x0b5f, 0x0b61,	// range
//0b66-0b6f // Digits
//0b70 // Symbol
};
#define OR_LANG_ORTH_SZ	39

// clang-format on
