// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int pa_lang_orth_chars[] = {
//
// fontconfig/fc-lang/pa.orth
//
// Copyright © 2004 Red Hat, Inc.
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Panjabi/Punjabi (pa)
//
// According to ISO 639-3, 'pa/pan' only applies to Panjabi as used in India:
//   http://www.sil.org/iso639-3/documentation.asp?id=pan
//
// For Panjabi as used in Pakistan, use 'lah' or 'pa-PK':
//   http://www.sil.org/iso639-3/documentation.asp?id=lah
//
// From Unicode coverage for Gurmukhi, with modifications based on
// the 'Lohit Punjabi' font
//
// 0A01-0A03	// Various signs
	0xf0f0ffff, 0x0a05, 0x0a0a,	// range	// Independent vowels
	0xf0f0ffff, 0x0a0f, 0x0a10,	// range
	0xf0f0ffff, 0x0a13, 0x0a14,	// range
	0xf0f0ffff, 0x0a15, 0x0a28,	// range	// Consonants
	0xf0f0ffff, 0x0a2a, 0x0a30,	// range
	0xf0f0ffff, 0x0a32, 0x0a33,	// range
	0xf0f0ffff, 0x0a35, 0x0a36,	// range
	0xf0f0ffff, 0x0a38, 0x0a39,	// range
	0x0a3c,		// Nukta
	0xf0f0ffff, 0x0a3e, 0x0a42,	// range	// Dependent vowel signs
	0xf0f0ffff, 0x0a47, 0x0a48,	// range
	0xf0f0ffff, 0x0a4b, 0x0a4c,	// range
	0x0a4d,		// Virama
	0xf0f0ffff, 0x0a59, 0x0a5c,	// range	// Additional consonants
// 0A5E		// GURMUKHI LETTER FA
// 0A66-0A6F	// Digits
	0xf0f0ffff, 0x0a70, 0x0a74,	// range	// Gurmukhi-specific additions
};
#define PA_LANG_ORTH_SZ	41

// clang-format on
