// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int pap_an_lang_orth_chars[] = {
//
// fontconfig/fc-lang/pap_an.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Papiamento in Netherlands Antilles (pap-AN)
//
// This is based on Curaçao orthography, also called "Papiamentu".
//
// Sources:
// * http://papiamentu.pbwiki.com/Pronunciation
// * http://en.wikipedia.org/wiki/Papiamento
// * http://papiamentu.donamaro.nl/
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c1,
	0xf0f0ffff, 0x00c8, 0x00c9,	// range
	0x00cd,
	0xf0f0ffff, 0x00d1, 0x00d3,	// range
	0xf0f0ffff, 0x00d9, 0x00da,	// range
	0x00dc,
	0x00e1,
	0xf0f0ffff, 0x00e8, 0x00e9,	// range
	0x00ed,
	0xf0f0ffff, 0x00f1, 0x00f3,	// range
	0xf0f0ffff, 0x00f9, 0x00fa,	// range
	0x00fc,
};
#define PAP_AN_LANG_ORTH_SZ	30

// clang-format on
