// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ps_pk_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ps_pk.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Pashto in Pakistan (PS-PK)
//
// Data from Roozbeh Pournader <roozbeh@sharif.edu>
//
// Since the Unicode Presentation Forms don't contain any of the
// Pashto-specific letters (that is Pashto letters not in Persian), we are
// going with the general forms instead of the Presentation forms, unlike
// Arabic, Persian, or Urdu.
//
	0xf0f0ffff, 0x0621, 0x0624,	// range
	0xf0f0ffff, 0x0626, 0x063a,	// range
	0xf0f0ffff, 0x0641, 0x0642,	// range
	0xf0f0ffff, 0x0644, 0x0648,	// range
	0x064a,
	0x067c,
	0x067e,
	0x0681,
	0xf0f0ffff, 0x0685, 0x0686,	// range
	0x0689,
	0x0693,
	0x0696,
	0x0698,
	0x069a,
	0x06a9,
	0x06ab,
	0x06bc,
	0x06cd,
	0x06d0,
	0x06d2,
};
#define PS_PK_LANG_ORTH_SZ	30

// clang-format on
