// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int sd_lang_orth_chars[] = {
//
// fontconfig/fc-lang/sd.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Sindhi (sd)
//
// Sindhi is mostly written in the Arabic script in both Pakistan and India.
//
// Sources:
// * http://www.user.uni-hannover.de/nhtcapri/sindhi-alphabet.html
// * http://www.omniglot.com/writing/sindhi.htm
// * http://tdil.mit.gov.in/sindhidesignguideoct02.pdf
//
// Some of the Sindhi letters are not available as presentation forms in
// Unicode, so we go with general-purpose Arabic letters.
//
	0xf0f0ffff, 0x0621, 0x0622,	// range
	0x0624,
	0xf0f0ffff, 0x0626, 0x0628,	// range
	0xf0f0ffff, 0x062a, 0x063a,	// range
	0xf0f0ffff, 0x0641, 0x0642,	// range
	0xf0f0ffff, 0x0644, 0x0648,	// range
	0x064a,
	0xf0f0ffff, 0x067a, 0x067b,	// range
	0xf0f0ffff, 0x067d, 0x0680,	// range
	0xf0f0ffff, 0x0683, 0x0684,	// range
	0xf0f0ffff, 0x0686, 0x0687,	// range
	0x068a,
	0xf0f0ffff, 0x068c, 0x068d,	// range
	0x068f,
	0x0699,
	0x06a6,
	0xf0f0ffff, 0x06a9, 0x06aa,	// range
	0x06af,
	0x06b1,
	0x06b3,
	0x06bb,
	0x06be,
//06FD-06FD // signs are usually not included in orthographies
};
#define SD_LANG_ORTH_SZ	44

// clang-format on
