
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int sg_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c2,
	0x00c4,
	0xf0f0ffff, 0x00ca, 0x00cb,	// range
	0xf0f0ffff, 0x00ce, 0x00cf,	// range
	0x00d4,
	0x00d6,
	0xf0f0ffff, 0x00db, 0x00dc,	// range
	0x00e2,
	0x00e4,
	0xf0f0ffff, 0x00ea, 0x00eb,	// range
	0xf0f0ffff, 0x00ee, 0x00ef,	// range
	0x00f4,
	0x00f6,
	0xf0f0ffff, 0x00fb, 0x00fc,	// range
};
#define SG_LANG_ORTH_SZ	32
