// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int sg_lang_orth_chars[] = {
//
// fontconfig/fc-lang/sg.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Sango (sg)
//
// Sources:
// * http://en.wikipedia.org/wiki/Sango_language
// * http://www.omniglot.com/writing/sango.php
//
// C, Q, and X are not used.
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c2,
	0x00c4,
	0xf0f0ffff, 0x00ca, 0x00cb,	// range
	0xf0f0ffff, 0x00ce, 0x00cf,	// range
	0x00d4,
	0x00d6,
	0xf0f0ffff, 0x00db, 0x00dc,	// range
	0x00e2,
	0x00e4,
	0xf0f0ffff, 0x00ea, 0x00eb,	// range
	0xf0f0ffff, 0x00ee, 0x00ef,	// range
	0x00f4,
	0x00f6,
	0xf0f0ffff, 0x00fb, 0x00fc,	// range
};
#define SG_LANG_ORTH_SZ	32

// clang-format on
