// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int si_lang_orth_chars[] = {
//
// fontconfig/fc-lang/si.orth
//
// Copyright © 2002 Keith Packard
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Sinhala/Sinhalese (si)
//
// The document SINHALA CHARACTER CODE FOR INFORMATION INTERCHANGE, PART 2:
// REQUIREMENTS AND METHODS OF TEST (SLS 1134:PART2:2007 UDC 003.035:003.336)
// describes three (3) levels of compliance for Unicode Sinhala fonts. The
// first level describes the minimum requirements for SLS certification. The
// third level includes the first and second level requirements and additional
// requirements.
//
// To get a copy of this document contact the Sri Lanka Standards Institution
// (http://www.slsi.lk/).
//
// The Unicode document: http://unicode.org/charts/PDF/U0D80.PDF
// describes the base for level 3 compliance.
//
// Level 1 compliance can be described as level 3 with the exclusion of:
// U+0D8F ILUYANNA (Independent Vowel)
// U+0D90 ILUUYANNA (Independent Vowel)
// U+0DDF GAYANUKITTA (Dependent Vowel)
// U+0DF3 DIGA GAYANUKITTA (Dependent Vowel)
// U+0DF4 KUNDDALIYA (Punctuation)
//
// Sinhala and SLS1134 experts can be contacted at:
// sinhala-technical at lists.sourceforge.net
// ltrl at ucsc.cmb.ac.lk
//
// Semi Consonants
	0xf0f0ffff, 0x0d82, 0x0d83,	// range
// Independent Vowels
	0xf0f0ffff, 0x0d85, 0x0d8d,	// range
// 0d8e IRUUYANNA (Level 1, but not in modern use)
// 0d8f ILUYANNA (Level 3)
// 0d90 ILUUYANNA (Level 3)
	0xf0f0ffff, 0x0d91, 0x0d96,	// range
// Consonants
	0xf0f0ffff, 0x0d9a, 0x0da5,	// range
//0da6 SANYAKA JAYANNA (Level 1, but not in modern use)
	0xf0f0ffff, 0x0da7, 0x0db1,	// range
	0xf0f0ffff, 0x0db3, 0x0dbb,	// range
	0x0dbd,
	0xf0f0ffff, 0x0dc0, 0x0dc6,	// range
// Dependent Vowels
	0x0dca,
	0xf0f0ffff, 0x0dcf, 0x0dd4,	// range
	0x0dd6,
	0xf0f0ffff, 0x0dd8, 0x0dde,	// range
// 0ddf GAYANUKITTA (Level 3)
	0x0df2,
// 0df3 DIGA GAYANUKITTA (Level 3)
// Punctuation
// 0df4 KUNDDALIYA (Level 3)
};
#define SI_LANG_ORTH_SZ	31

// clang-format on
