// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int sv_lang_orth_chars[] = {
//
// fontconfig/fc-lang/sv.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Swedish (SV)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
// evertype.com includes a large number of additional precomposed letters
// not marked by eki.ee; I've left those commented out here
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
//00bb
	0x00c0,
	0x00c1,
//00c2
//00c3
	0x00c4,
	0x00c5,
//00c6
//00c7
//00c8
	0x00c9,
//00ca
	0x00cb,
//00cc
//00cd
//00ce
//00cf
//00d0
//00d1
//00d2
//00d3
//00d4
	0x00d6,
//00d7
//00d8
//00d9
//00da
//00db
	0x00dc,
//00dd
	0x00e0,
	0x00e1,
//00e2
//00e3
	0x00e4,
	0x00e5,
//00e6
//00e7
//00e8
	0x00e9,
//00ea
	0x00eb,
//00ec
//00ed
//00ee
//00ef
//00f0
//00f1
//00f2
//00f3
//00f4
	0x00f6,
//00f8
//00f9
//00fa
//00fb
	0x00fc,
//00fd
//0106-0107	// C, c with acute
//010c-010d	// C, c with caron
//0141-0144	// L, l with stroke  N, n with acute
//0158-015b	// R, r with caron   S, s with acute
//0160-0161	// S, s with caron
//2019	// single quote
//201d	// double quote
//203a	// angle quote
};
#define SV_LANG_ORTH_SZ	22

// clang-format on
