// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ta_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ta.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Tamil (TA)
//
// Taken from the Unicode coverage of this language
//
// updates from Jungshik Shin <jshin@mailaps.org>
//
//0b82		// not present in many Tamil fonts
	0x0b83,
	0xf0f0ffff, 0x0b85, 0x0b8a,	// range
	0xf0f0ffff, 0x0b8e, 0x0b90,	// range
	0xf0f0ffff, 0x0b92, 0x0b95,	// range
	0xf0f0ffff, 0x0b99, 0x0b9a,	// range
	0x0b9c,
	0xf0f0ffff, 0x0b9e, 0x0b9f,	// range
	0xf0f0ffff, 0x0ba3, 0x0ba4,	// range
	0xf0f0ffff, 0x0ba8, 0x0baa,	// range
	0xf0f0ffff, 0x0bae, 0x0bb5,	// range
	0xf0f0ffff, 0x0bb7, 0x0bb9,	// range
	0xf0f0ffff, 0x0bbe, 0x0bc2,	// range
	0xf0f0ffff, 0x0bc6, 0x0bc8,	// range
	0xf0f0ffff, 0x0bca, 0x0bcd,	// range
	0x0bd7,
//0be7-0bf2	// Tamil digits and numbers
};
#define TA_LANG_ORTH_SZ	39

// clang-format on
