// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int te_lang_orth_chars[] = {
//
// fontconfig/fc-lang/te.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Telugu (te)
//
// Taken from the Unicode coverage of this language
//
	0xf0f0ffff, 0x0c01, 0x0c03,	// range
	0xf0f0ffff, 0x0c05, 0x0c0c,	// range
	0xf0f0ffff, 0x0c0e, 0x0c10,	// range
	0xf0f0ffff, 0x0c12, 0x0c28,	// range
	0xf0f0ffff, 0x0c2a, 0x0c33,	// range
	0xf0f0ffff, 0x0c35, 0x0c39,	// range
	0xf0f0ffff, 0x0c3e, 0x0c44,	// range
	0xf0f0ffff, 0x0c46, 0x0c48,	// range
	0xf0f0ffff, 0x0c4a, 0x0c4d,	// range
	0xf0f0ffff, 0x0c55, 0x0c56,	// range
	0xf0f0ffff, 0x0c60, 0x0c61,	// range
//0c66-0c6f // Digits
};
#define TE_LANG_ORTH_SZ	33

// clang-format on
