// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int tk_lang_orth_chars[] = {
//
// fontconfig/fc-lang/tk.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Turkmen (tk)
//
// Sources:
// http://www.omniglot.com/writing/turkmen.htm
// http://www.itscj.ipsj.or.jp/ISO-IR/230.pdf
// http://www.eki.ee/wgrs/rom2_tk.htm
//
// C, Q, V, and X are not used
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c4,
	0x00c7,
	0x00d6,
	0xf0f0ffff, 0x00dc, 0x00dd,	// range
	0x00e4,
	0x00e7,
	0x00f6,
	0xf0f0ffff, 0x00fc, 0x00fd,	// range
	0xf0f0ffff, 0x0147, 0x0148,	// range
	0xf0f0ffff, 0x015e, 0x015f,	// range
	0xf0f0ffff, 0x017d, 0x017e,	// range
};
#define TK_LANG_ORTH_SZ	27

// clang-format on
