// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int tr_lang_orth_chars[] = {
//
// fontconfig/fc-lang/tr.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Turkish (TR)
//
// Sources:
//	www.evertype.com
//	www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c2,//	LATIN CAPITAL LETTER A WITH CIRCUMFLEX
	0x00c7,//	LATIN CAPITAL LETTER C WITH CEDILLA
	0x00ce,//	LATIN CAPITAL LETTER I WITH CIRCUMFLEX
	0x00d6,//	LATIN CAPITAL LETTER O WITH DIAERESIS
	0x00db,//	LATIN CAPITAL LETTER U WITH CIRCUMFLEX
	0x00dc,//	LATIN CAPITAL LETTER U WITH DIAERESIS
	0x00e2,//	LATIN SMALL LETTER A WITH CIRCUMFLEX
	0x00e7,//	LATIN SMALL LETTER C WITH CEDILLA
	0x00ee,//	LATIN SMALL LETTER I WITH CIRCUMFLEX
	0x00f6,//	LATIN SMALL LETTER O WITH DIAERESIS
	0x00fb,//	LATIN SMALL LETTER U WITH CIRCUMFLEX
	0x00fc,//	LATIN SMALL LETTER U WITH DIAERESIS
	0x011e,//	LATIN CAPITAL LETTER G WITH BREVE
	0x011f,//	LATIN SMALL LETTER G WITH BREVE
	0x0130,//	LATIN CAPITAL LETTER I WITH DOT ABOVE
	0x0131,//	LATIN SMALL LETTER DOTLESS I
	0x015e,//	LATIN CAPITAL LETTER S WITH CEDILLA *
	0x015f,//	LATIN SMALL LETTER S WITH CEDILLA *
};
#define TR_LANG_ORTH_SZ	24

// clang-format on
