// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ty_lang_orth_chars[] = {
//
// fontconfig/fc-lang/ty.orth
//
// Copyright © 2009 Roozbeh Pournader
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The author(s) make(s) no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIM(S) ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Tahitian (ty)
//
// Sources:
// * http://www.omniglot.com/writing/tahitian.htm
// * http://en.wikipedia.org/wiki/Tahitian_language
//
// B, C, D, G, J, K, L, Q, S, W, X, Y and Z are not used.
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00cf, // used in one word only?
	0x00ef, // used in one word only?
	0xf0f0ffff, 0x0100, 0x0101,	// range
	0xf0f0ffff, 0x0112, 0x0113,	// range
	0xf0f0ffff, 0x012a, 0x012b,	// range
	0xf0f0ffff, 0x014c, 0x014d,	// range
	0xf0f0ffff, 0x016a, 0x016b,	// range
	0x02bc, // or possibly 02BB
};
#define TY_LANG_ORTH_SZ	24

// clang-format on
