
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int ty_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00cf,
	0x00ef,
	0xf0f0ffff, 0x0100, 0x0101,	// range
	0xf0f0ffff, 0x0112, 0x0113,	// range
	0xf0f0ffff, 0x012a, 0x012b,	// range
	0xf0f0ffff, 0x014c, 0x014d,	// range
	0xf0f0ffff, 0x016a, 0x016b,	// range
	0x02bc,
};
#define TY_LANG_ORTH_SZ	24
