// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int und_zmth_lang_orth_chars[] = {
//
// fontconfig/fc-lang/emoji.orth
//
// Copyright © 2002 Keith Packard
// Copyright © 2017 Red Hat, Inc.
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Math
//
// based on
// http://www.unicode.org/Public/math/revision-9/MathClass-9.txt
//
	0x0020,//	#	S 	//  	SPACE
	0x0021,//	#	P 	// !	EXCLAMATION MARK
	0x0021,//	#	N 	// !	EXCLAMATION MARK
	0xf0f0ffff, 0x0023, 0x0026,	// range//	#	N 	# //..&	NUMBER SIGN..AMPERSAND
	0x0028,//	#	O 	// (	LEFT PARENTHESIS
	0x0029,//	#	C 	// )	RIGHT PARENTHESIS
	0x002a,//	#	N 	// *	ASTERISK
	0x002b,//	#	V 	// +	PLUS SIGN
	0x002c,//	#	P 	// ,	COMMA
	0x002d,//	#	R 	// -	HYPHEN-MINUS
	0x002e,//	#	P 	// .	FULL STOP
	0x002f,//	#	R 	// /	SOLIDUS
	0xf0f0ffff, 0x0030, 0x0039,	// range//	#	N 	// 0..9	DIGIT ZERO..NINE
	0xf0f0ffff, 0x003a, 0x003b,	// range//	#	P 	# :..	//	COLON..SEMICOLON
	0xf0f0ffff, 0x003c, 0x003e,	// range//	#	R 	// <..>	LESS-THAN SIGN..GREATER-THAN SIGN
	0x003f,//	#	P 	// ?	QUESTION MARK
	0x0040,//	#	N 	// @	COMMERCIAL AT
	0xf0f0ffff, 0x0041, 0x005a,	// range//	#	A 	// A..Z	LATIN CAPITAL LETTER A..Z
	0x005b,//	#	O 	// [	LEFT SQUARE BRACKET
	0x005c,//	#	N 	// \	REVERSE SOLIDUS
	0x005d,//	#	C 	// ]	RIGHT SQUARE BRACKET
	0x005e,//	#	X 	// ^	CIRCUMFLEX ACCENT
	0xf0f0ffff, 0x0061, 0x007a,	// range//	#	A 	// a..z	LATIN SMALL LETTER A..Z
	0x007b,//	#	O 	// {	LEFT CURLY BRACKET
	0x007c,//	#	F 	// |	VERTICAL LINE
	0x007d,//	#	C 	// }	RIGHT CURLY BRACKET
	0x007e,//	#	X 	// ~	TILDE
	0x00a1,//	#	P 	// ¡	INVERTED EXCLAMATION MARK
	0xf0f0ffff, 0x00a2, 0x00a7,	// range//	#	N 	// ¢..§	CENT SIGN..SECTION SIGN
	0x00ac,//	#	N 	// ¬	NOT SIGN
	0x00b0,//	#	N 	// °	DEGREE SIGN
	0x00b1,//	#	V 	// ±	PLUS-MINUS SIGN
	0xf0f0ffff, 0x00b5, 0x00b6,	// range//	#	N 	// µ..¶	MICRO SIGN..PILCROW SIGN
	0x00b7,//	#	B 	// ·	MIDDLE DOT
	0x00bf,//	#	P 	// ¿	INVERTED QUESTION MARK
	0x00d7,//	#	B 	// ×	MULTIPLICATION SIGN
	0x00f7,//	#	B 	// ÷	DIVISION SIGN
	0x0131,//	#	A 	// ı	LATIN SMALL LETTER DOTLESS I
	0x0308,//	#	D 	// ̈	COMBINING DIAERESIS
	0x030a,//	#	D 	// ̊	COMBINING RING ABOVE
	0x030c,//	#	D 	// ̌	COMBINING CARON
	0x0338,//	#	D 	// ̸	COMBINING LONG SOLIDUS OVERLAY
	0xf0f0ffff, 0x0391, 0x03a1,	// range//	#	A 	// Α..Ρ	GREEK CAPITAL LETTER ALPHA..RHO
	0xf0f0ffff, 0x03a3, 0x03a4,	// range//	#	A 	// Σ..Τ	GREEK CAPITAL LETTER SIGMA..TAU
	0xf0f0ffff, 0x03a6, 0x03a9,	// range//	#	A 	// Φ..Ω	GREEK CAPITAL LETTER PHI..OMEGA
	0xf0f0ffff, 0x03b1, 0x03c1,	// range//	#	A 	// α..ρ	GREEK SMALL LETTER ALPHA..RHO
	0xf0f0ffff, 0x03c3, 0x03c9,	// range//	#	A 	// σ..ω	GREEK SMALL LETTER SIGMA..OMEGA
	0xf0f0ffff, 0x03d5, 0x03d6,	// range//	#	A 	// ϕ..ϖ	GREEK PHI SYMBOL..PI SYMBOL
	0xf0f0ffff, 0x03f0, 0x03f1,	// range//	#	A 	// ϰ..ϱ	GREEK KAPPA SYMBOL..RHO SYMBOL
	0x2016,//	#	F 	// ‖	DOUBLE VERTICAL LINE
	0x2020,//	#	R 	// †	DAGGER
	0x2020,//	#	N 	// †	DAGGER
	0x2021,//	#	R 	// ‡	DOUBLE DAGGER
	0x2021,//	#	N 	// ‡	DOUBLE DAGGER
	0x2022,//	#	B 	// •	BULLET
	0x2026,//	#	N 	// …	HORIZONTAL ELLIPSIS
	0x2044,//	#	X 	// ⁄	FRACTION SLASH
	0x2057,//	#	N 	// ⁗	QUADRUPLE PRIME
	0x20e1,//	#	D 	// ⃡	COMBINING LEFT RIGHT ARROW ABOVE
	0x2102,//	#	A 	// ℂ	DOUBLE-STRUCK CAPITAL C
	0xf0f0ffff, 0x210e, 0x210f,	// range//	#	N 	// ℎ..ℏ	PLANCK CONSTANT.. OVER TWO PI
	0xf0f0ffff, 0x2110, 0x2113,	// range//	#	A 	// ℐ..ℓ	SCRIPT CAPITAL I..SMALL L
	0x2115,//	#	A 	// ℕ	DOUBLE-STRUCK CAPITAL N
	0xf0f0ffff, 0x2118, 0x211d,	// range//	#	A 	// ℘..ℝ	SCRIPT CAPITAL P..DOUBLE-STRUCK CAPITAL R
	0x2124,//	#	A 	// ℤ	DOUBLE-STRUCK CAPITAL Z
	0xf0f0ffff, 0x2200, 0x2201,	// range//	#	U 	// ∀..∁	FOR ALL..COMPLEMENT
	0x2202,//	#	N 	// ∂	PARTIAL DIFFERENTIAL
	0xf0f0ffff, 0x2203, 0x2204,	// range//	#	U 	// ∃..∄	THERE EXISTS..DOES NOT EXIST
	0x2205,//	#	N 	// ∅	EMPTY SET
	0xf0f0ffff, 0x2206, 0x2207,	// range//	#	U 	// ∆..∇	INCREMENT..NABLA
	0xf0f0ffff, 0x2208, 0x220d,	// range//	#	R 	// ∈..∍	ELEMENT OF..SMALL CONTAINS AS MEMBER
	0xf0f0ffff, 0x220f, 0x2211,	// range//	#	L 	// ∏..∑	N-ARY PRODUCT..SUMMATION
	0xf0f0ffff, 0x2212, 0x2213,	// range//	#	V 	// −..∓	MINUS SIGN..MINUS-OR-PLUS SIGN
	0xf0f0ffff, 0x2214, 0x2219,	// range//	#	B 	// ∔..∙	DOT PLUS..BULLET OPERATOR
	0x221d,//	#	R 	// ∝	PROPORTIONAL TO
	0xf0f0ffff, 0x221e, 0x2222,	// range//	#	N 	// ∞..∢	INFINITY..SPHERICAL ANGLE
	0xf0f0ffff, 0x2223, 0x2226,	// range//	#	R 	// ∣..∦	DIVIDES..NOT PARALLEL TO
	0xf0f0ffff, 0x2227, 0x222a,	// range//	#	B 	// ∧..∪	LOGICAL AND..UNION
	0xf0f0ffff, 0x2234, 0x2235,	// range//	#	N 	// ∴..∵	THEREFORE..BECAUSE
	0xf0f0ffff, 0x2236, 0x2237,	// range//	#	R 	// ∶..∷	RATIO..PROPORTION
	0x2238,//	#	B 	// ∸	DOT MINUS
	0xf0f0ffff, 0x2239, 0x223d,	// range//	#	R 	// ∹..∽	EXCESS..REVERSED TILDE
	0x223e,//	#	B 	// ∾	INVERTED LAZY S
	0x223f,//	#	N 	// ∿	SINE WAVE
	0x2240,//	#	B 	// ≀	WREATH PRODUCT
	0xf0f0ffff, 0x228c, 0x228e,	// range//	#	B 	// ⊌..⊎	MULTISET.. UNION
	0xf0f0ffff, 0x228f, 0x2292,	// range//	#	R 	// ⊏..⊒	SQUARE IMAGE OF..ORIGINAL OF OR EQUAL TO
	0xf0f0ffff, 0x2293, 0x22a1,	// range//	#	B 	// ⊓..⊡	SQUARE CAP..SQUARED DOT OPERATOR
	0xf0f0ffff, 0x22a2, 0x22a3,	// range//	#	R 	// ⊢..⊣	RIGHT TACK..LEFT TACK
	0xf0f0ffff, 0x22a4, 0x22a5,	// range//	#	N 	// ⊤..⊥	DOWN TACK..UP TACK
	0xf0f0ffff, 0x22c0, 0x22c3,	// range//	#	L 	// ⋀..⋃	N-ARY LOGICAL AND..UNION
	0x22c8,//	#	R 	// ⋈	BOWTIE
	0x22cd,//	#	R 	// ⋍	REVERSED TILDE EQUALS
	0xf0f0ffff, 0x22ce, 0x22cf,	// range//	#	B 	// ⋎..⋏	CURLY LOGICAL OR..AND
	0x2308,//	#	O 	// ⌈	LEFT CEILING
	0x2309,//	#	C 	// ⌉	RIGHT CEILING
	0x230a,//	#	O 	// ⌊	LEFT FLOOR
	0x230b,//	#	C 	// ⌋	RIGHT FLOOR
	0xf0f0ffff, 0x2322, 0x2323,	// range//	#	R 	// ⌢..⌣	FROWN..SMILE
	0xf0f0ffff, 0x25a0, 0x25a1,	// range//	#	N 	// ■..□	BLACK SQUARE..WHITE SQUARE
	0x27e6,//	#	O 	// ⟦	MATHEMATICAL LEFT WHITE SQUARE BRACKET
	0x27e7,//	#	C 	// ⟧	MATHEMATICAL RIGHT WHITE SQUARE BRACKET
	0x27e8,//	#	O 	// ⟨	MATHEMATICAL LEFT ANGLE BRACKET
	0x27e9,//	#	C 	// ⟩	MATHEMATICAL RIGHT ANGLE BRACKET
	0xf0f0ffff, 0x1d400, 0x1d454,	// range//	#	A 	// 𝐀..𝑔	MATHEMATICAL BOLD CAPITAL A..ITALIC SMALL G
	0xf0f0ffff, 0x1d456, 0x1d49c,	// range//	#	A 	// 𝑖..𝒜	MATHEMATICAL ITALIC SMALL I..SCRIPT CAPITAL A
	0xf0f0ffff, 0x1d49e, 0x1d49f,	// range//	#	A 	// 𝒞..𝒟	MATHEMATICAL SCRIPT CAPITAL C..D
	0x1d4a2,//	#	A 	// 𝒢	MATHEMATICAL SCRIPT CAPITAL G
	0xf0f0ffff, 0x1d4a5, 0x1d4a6,	// range//	#	A 	// 𝒥..𝒦	MATHEMATICAL SCRIPT CAPITAL J..K
	0xf0f0ffff, 0x1d4a9, 0x1d4ac,	// range//	#	A 	// 𝒩..𝒬	MATHEMATICAL SCRIPT CAPITAL N..Q
	0xf0f0ffff, 0x1d53b, 0x1d53e,	// range//	#	A 	// 𝔻..𝔾	MATHEMATICAL DOUBLE-STRUCK CAPITAL D..G
	0xf0f0ffff, 0x1d540, 0x1d544,	// range//	#	A 	// 𝕀..𝕄	MATHEMATICAL DOUBLE-STRUCK CAPITAL I..M
	0x1d546,//	#	A 	// 𝕆	MATHEMATICAL DOUBLE-STRUCK CAPITAL O
	0xf0f0ffff, 0x1d54a, 0x1d550,	// range//	#	A 	// 𝕊..𝕐	MATHEMATICAL DOUBLE-STRUCK CAPITAL S..Y
	0xf0f0ffff, 0x1d6a4, 0x1d6a5,	// range//	#	A 	// 𝚤..𝚥	MATHEMATICAL ITALIC SMALL DOTLESS I..J
};
#define UND_ZMTH_LANG_ORTH_SZ	213

// clang-format on
