// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int und_zsye_lang_orth_chars[] = {
//
// fontconfig/fc-lang/emoji.orth
//
// Copyright © 2002 Keith Packard
// Copyright © 2017 Red Hat, Inc.
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Emoji
//
// http://unicode.org/Public/emoji/5.0/emoji-data.txt
// with anything after Unicode 6.0 commented out.
//
//// Emoji Presentation
	0xf0f0ffff, 0x231a, 0x231b,	// range    	//  1.1  [2] (⌚..⌛)    watch..hourglass
	0xf0f0ffff, 0x23e9, 0x23ec,	// range    	//  6.0  [4] (⏩..⏬)    fast-forward button..fast down button
	0x23f0,          	//  6.0  [1] (⏰)       alarm clock
	0x23f3,          	//  6.0  [1] (⏳)       hourglass with flowing sand
	0xf0f0ffff, 0x25fd, 0x25fe,	// range    	//  3.2  [2] (◽..◾)    white medium-small square..black medium-small square
	0xf0f0ffff, 0x2614, 0x2615,	// range    	//  4.0  [2] (☔..☕)    umbrella with rain drops..hot beverage
	0xf0f0ffff, 0x2648, 0x2653,	// range    	//  1.1 [12] (♈..♓)    Aries..Pisces
	0x267f,          	//  4.1  [1] (♿)       wheelchair symbol
	0x2693,          	//  4.1  [1] (⚓)       anchor
	0x26a1,          	//  4.0  [1] (⚡)       high voltage
	0xf0f0ffff, 0x26aa, 0x26ab,	// range    	//  4.1  [2] (⚪..⚫)    white circle..black circle
	0xf0f0ffff, 0x26bd, 0x26be,	// range    	//  5.2  [2] (⚽..⚾)    soccer ball..baseball
	0xf0f0ffff, 0x26c4, 0x26c5,	// range    	//  5.2  [2] (⛄..⛅)    snowman without snow..sun behind cloud
	0x26ce,          	//  6.0  [1] (⛎)       Ophiuchus
	0x26d4,          	//  5.2  [1] (⛔)       no entry
	0x26ea,          	//  5.2  [1] (⛪)       church
	0xf0f0ffff, 0x26f2, 0x26f3,	// range    	//  5.2  [2] (⛲..⛳)    fountain..flag in hole
	0x26f5,          	//  5.2  [1] (⛵)       sailboat
	0x26fa,          	//  5.2  [1] (⛺)       tent
	0x26fd,          	//  5.2  [1] (⛽)       fuel pump
	0x2705,          	//  6.0  [1] (✅)       white heavy check mark
	0xf0f0ffff, 0x270a, 0x270b,	// range    	//  6.0  [2] (✊..✋)    raised fist..raised hand
	0x2728,          	//  6.0  [1] (✨)       sparkles
	0x274c,          	//  6.0  [1] (❌)       cross mark
	0x274e,          	//  6.0  [1] (❎)       cross mark button
	0xf0f0ffff, 0x2753, 0x2755,	// range    	//  6.0  [3] (❓..❕)    question mark..white exclamation mark
	0x2757,          	//  5.2  [1] (❗)       exclamation mark
	0xf0f0ffff, 0x2795, 0x2797,	// range    	//  6.0  [3] (➕..➗)    heavy plus sign..heavy division sign
	0x27b0,          	//  6.0  [1] (➰)       curly loop
	0x27bf,          	//  6.0  [1] (➿)       double curly loop
	0xf0f0ffff, 0x2b1b, 0x2b1c,	// range    	//  5.1  [2] (⬛..⬜)    black large square..white large square
	0x2b50,          	//  5.1  [1] (⭐)       white medium star
	0x2b55,          	//  5.2  [1] (⭕)       heavy large circle
	0x1f004,         	//  5.1  [1] (🀄)       mahjong red dragon
	0x1f0cf,         	//  6.0  [1] (🃏)       joker
	0x1f18e,         	//  6.0  [1] (🆎)       AB button (blood type)
	0xf0f0ffff, 0x1f191, 0x1f19a,	// range  	//  6.0 [10] (🆑..🆚)    CL button..VS button
	0xf0f0ffff, 0x1f1e6, 0x1f1ff,	// range  	//  6.0 [26] (🇦..🇿)    regional indicator symbol letter a..regional indicator symbol letter z
	0x1f201,         	//  6.0  [1] (🈁)       Japanese “here” button
	0x1f21a,         	//  5.2  [1] (🈚)       Japanese “free of charge” button
	0x1f22f,         	//  5.2  [1] (🈯)       Japanese “reserved” button
	0xf0f0ffff, 0x1f232, 0x1f236,	// range  	//  6.0  [5] (🈲..🈶)    Japanese “prohibited” button..Japanese “not free of charge” button
	0xf0f0ffff, 0x1f238, 0x1f23a,	// range  	//  6.0  [3] (🈸..🈺)    Japanese “application” button..Japanese “open for business” button
	0xf0f0ffff, 0x1f250, 0x1f251,	// range  	//  6.0  [2] (🉐..🉑)    Japanese “bargain” button..Japanese “acceptable” button
	0xf0f0ffff, 0x1f300, 0x1f320,	// range  	//  6.0 [33] (🌀..🌠)    cyclone..shooting star
// 1F32D..1F32F  	//  8.0  [3] (🌭..🌯)    hot dog..burrito
	0xf0f0ffff, 0x1f330, 0x1f335,	// range  	//  6.0  [6] (🌰..🌵)    chestnut..cactus
	0xf0f0ffff, 0x1f337, 0x1f37c,	// range  	//  6.0 [70] (🌷..🍼)    tulip..baby bottle
// 1F37E..1F37F  	//  8.0  [2] (🍾..🍿)    bottle with popping cork..popcorn
	0xf0f0ffff, 0x1f380, 0x1f393,	// range  	//  6.0 [20] (🎀..🎓)    ribbon..graduation cap
	0xf0f0ffff, 0x1f3a0, 0x1f3c4,	// range  	//  6.0 [37] (🎠..🏄)    carousel horse..person surfing
// 1F3C5         	//  7.0  [1] (🏅)       sports medal
	0xf0f0ffff, 0x1f3c6, 0x1f3ca,	// range  	//  6.0  [5] (🏆..🏊)    trophy..person swimming
// 1F3CF..1F3D3  	//  8.0  [5] (🏏..🏓)    cricket..ping pong
	0xf0f0ffff, 0x1f3e0, 0x1f3f0,	// range  	//  6.0 [17] (🏠..🏰)    house..castle
// 1F3F4         	//  7.0  [1] (🏴)       black flag
// 1F3F8..1F3FF  	//  8.0  [8] (🏸..🏿)    badminton..dark skin tone
// 1F400..1F43E  	//  6.0 [63] (🐀..🐾)    rat..paw prints
	0x1f440,         	//  6.0  [1] (👀)       eyes
	0xf0f0ffff, 0x1f442, 0x1f4f7,	// range  	//  6.0[182] (👂..📷)    ear..camera
// 1F4F8         	//  7.0  [1] (📸)       camera with flash
	0xf0f0ffff, 0x1f4f9, 0x1f4fc,	// range  	//  6.0  [4] (📹..📼)    video camera..videocassette
// 1F4FF         	//  8.0  [1] (📿)       prayer beads
	0xf0f0ffff, 0x1f500, 0x1f53d,	// range  	//  6.0 [62] (🔀..🔽)    shuffle tracks button..down button
// 1F54B..1F54E  	//  8.0  [4] (🕋..🕎)    kaaba..menorah
	0xf0f0ffff, 0x1f550, 0x1f567,	// range  	//  6.0 [24] (🕐..🕧)    one o’clock..twelve-thirty
// 1F57A         	//  9.0  [1] (🕺)       man dancing
// 1F595..1F596  	//  7.0  [2] (🖕..🖖)    middle finger..vulcan salute
// 1F5A4         	//  9.0  [1] (🖤)       black heart
	0xf0f0ffff, 0x1f5fb, 0x1f5ff,	// range  	//  6.0  [5] (🗻..🗿)    mount fuji..moai
// 1F600         	//  6.1  [1] (😀)       grinning face
	0xf0f0ffff, 0x1f601, 0x1f610,	// range  	//  6.0 [16] (😁..😐)    grinning face with smiling eyes..neutral face
// 1F611         	//  6.1  [1] (😑)       expressionless face
	0xf0f0ffff, 0x1f612, 0x1f614,	// range  	//  6.0  [3] (😒..😔)    unamused face..pensive face
// 1F615         	//  6.1  [1] (😕)       confused face
	0x1f616,         	//  6.0  [1] (😖)       confounded face
// 1F617         	//  6.1  [1] (😗)       kissing face
	0x1f618,         	//  6.0  [1] (😘)       face blowing a kiss
// 1F619         	//  6.1  [1] (😙)       kissing face with smiling eyes
	0x1f61a,         	//  6.0  [1] (😚)       kissing face with closed eyes
// 1F61B         	//  6.1  [1] (😛)       face with stuck-out tongue
	0xf0f0ffff, 0x1f61c, 0x1f61e,	// range  	//  6.0  [3] (😜..😞)    face with stuck-out tongue & winking eye..disappointed face
// 1F61F         	//  6.1  [1] (😟)       worried face
	0xf0f0ffff, 0x1f620, 0x1f625,	// range  	//  6.0  [6] (😠..😥)    angry face..disappointed but relieved face
// 1F626..1F627  	//  6.1  [2] (😦..😧)    frowning face with open mouth..anguished face
	0xf0f0ffff, 0x1f628, 0x1f62b,	// range  	//  6.0  [4] (😨..😫)    fearful face..tired face
// 1F62C         	//  6.1  [1] (😬)       grimacing face
	0x1f62d,         	//  6.0  [1] (😭)       loudly crying face
// 1F62E..1F62F  	//  6.1  [2] (😮..😯)    face with open mouth..hushed face
	0xf0f0ffff, 0x1f630, 0x1f633,	// range  	//  6.0  [4] (😰..😳)    face with open mouth & cold sweat..flushed face
// 1F634         	//  6.1  [1] (😴)       sleeping face
	0xf0f0ffff, 0x1f635, 0x1f640,	// range  	//  6.0 [12] (😵..🙀)    dizzy face..weary cat face
// 1F641..1F642  	//  7.0  [2] (🙁..🙂)    slightly frowning face..slightly smiling face
// 1F643..1F644  	//  8.0  [2] (🙃..🙄)    upside-down face..face with rolling eyes
	0xf0f0ffff, 0x1f645, 0x1f64f,	// range  	//  6.0 [11] (🙅..🙏)    person gesturing NO..folded hands
// 1F680..1F6C5  	//  6.0 [70] (🚀..🛅)    rocket..left luggage
// 1F6CC         	//  7.0  [1] (🛌)       person in bed
// 1F6D0         	//  8.0  [1] (🛐)       place of worship
// 1F6D1..1F6D2  	//  9.0  [2] (🛑..🛒)    stop sign..shopping cart
// 1F6EB..1F6EC  	//  7.0  [2] (🛫..🛬)    airplane departure..airplane arrival
// 1F6F4..1F6F6  	//  9.0  [3] (🛴..🛶)    kick scooter..canoe
// 1F6F7..1F6F8  	// 10.0  [2] (🛷..🛸)    sled..flying saucer
// 1F910..1F918  	//  8.0  [9] (🤐..🤘)    zipper-mouth face..sign of the horns
// 1F919..1F91E  	//  9.0  [6] (🤙..🤞)    call me hand..crossed fingers
// 1F91F         	// 10.0  [1] (🤟)       love-you gesture
// 1F920..1F927  	//  9.0  [8] (🤠..🤧)    cowboy hat face..sneezing face
// 1F928..1F92F  	// 10.0  [8] (🤨..🤯)    face with raised eyebrow..exploding head
// 1F930         	//  9.0  [1] (🤰)       pregnant woman
// 1F931..1F932  	// 10.0  [2] (🤱..🤲)    breast-feeding..palms up together
// 1F933..1F93A  	//  9.0  [8] (🤳..🤺)    selfie..person fencing
// 1F93C..1F93E  	//  9.0  [3] (🤼..🤾)    people wrestling..person playing handball
// 1F940..1F945  	//  9.0  [6] (🥀..🥅)    wilted flower..goal net
// 1F947..1F94B  	//  9.0  [5] (🥇..🥋)    1st place medal..martial arts uniform
// 1F94C         	// 10.0  [1] (🥌)       curling stone
// 1F950..1F95E  	//  9.0 [15] (🥐..🥞)    croissant..pancakes
// 1F95F..1F96B  	// 10.0 [13] (🥟..🥫)    dumpling..canned food
// 1F980..1F984  	//  8.0  [5] (🦀..🦄)    crab..unicorn face
// 1F985..1F991  	//  9.0 [13] (🦅..🦑)    eagle..squid
// 1F992..1F997  	// 10.0  [6] (🦒..🦗)    giraffe..cricket
// 1F9C0         	//  8.0  [1] (🧀)       cheese wedge
// 1F9D0..1F9E6  	// 10.0 [23] (🧐..🧦)    face with monocle..socks
};
#define UND_ZSYE_LANG_ORTH_SZ	145

// clang-format on
