
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int vo_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x0050,	// range
	0xf0f0ffff, 0x0052, 0x0056,	// range
	0xf0f0ffff, 0x0058, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x0070,	// range
	0xf0f0ffff, 0x0072, 0x0076,	// range
	0xf0f0ffff, 0x0078, 0x007a,	// range
	0x00c4,
	0x00d6,
	0x00dc,
	0x00e4,
	0x00f6,
	0x00fc,
};
#define VO_LANG_ORTH_SZ	24
