// clang-format off

// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/-/tree/main/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int wen_lang_orth_chars[] = {
//
// fontconfig/fc-lang/wen.orth
//
// Copyright © 2002 Keith Packard
//
// Permission to use, copy, modify, distribute, and sell this software and its
// documentation for any purpose is hereby granted without fee, provided that
// the above copyright notice appear in all copies and that both that
// copyright notice and this permission notice appear in supporting
// documentation, and that the name of the author(s) not be used in
// advertising or publicity pertaining to distribution of the software without
// specific, written prior permission.  The authors make no
// representations about the suitability of this software for any purpose.  It
// is provided "as is" without express or implied warranty.
//
// THE AUTHOR(S) DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE,
// INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO
// EVENT SHALL THE AUTHOR(S) BE LIABLE FOR ANY SPECIAL, INDIRECT OR
// CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
// DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
// TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
// PERFORMANCE OF THIS SOFTWARE.
//
// Sorbian languages (lower and upper) (WEN)
//
// Orthography from http://www.eki.ee/letter
//
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0xf0f0ffff, 0x0106, 0x0107,	// range
	0xf0f0ffff, 0x010c, 0x010d,	// range
	0xf0f0ffff, 0x011a, 0x011b,	// range
	0xf0f0ffff, 0x0141, 0x0142,	// range
	0xf0f0ffff, 0x0143, 0x0144,	// range
	0x00d3,
	0x00f3,
	0xf0f0ffff, 0x0154, 0x0155,	// range
	0xf0f0ffff, 0x0158, 0x0159,	// range
	0xf0f0ffff, 0x015a, 0x015b,	// range
	0xf0f0ffff, 0x0160, 0x0161,	// range
	0xf0f0ffff, 0x0179, 0x017a,	// range
	0xf0f0ffff, 0x017d, 0x017e,	// range
};
#define WEN_LANG_ORTH_SZ	41

// clang-format on
