
// This file is autogenerated from fc-lang database.
// https://www.freedesktop.org/wiki/Software/fontconfig/
// https://gitlab.freedesktop.org/fontconfig/fontconfig/tree/master/fc-lang
// by convert utility from https://github.com/virxkane/freetype_textdraw

const unsigned int wo_lang_orth_chars[] = {
	0xf0f0ffff, 0x0041, 0x005a,	// range
	0xf0f0ffff, 0x0061, 0x007a,	// range
	0x00c0,
	0x00e0,
	0x00c3,
	0x00e3,
	0x00c9,
	0x00e9,
	0x00cb,
	0x00eb,
	0x00d1,
	0x00f1,
	0xf0f0ffff, 0x014a, 0x014b,	// range
	0x00d3,
	0x00f3,
};
#define WO_LANG_ORTH_SZ	21
