#!/bin/sh

sdk="/opt/android-sdk-update-manager"
binclass_path=../app/build/intermediates/javac/debug/compileDebugJavaWithJavac/classes

export CLASSPATH="${CLASSPATH}:${sdk}/platforms/android-17/*:${binclass_path}"

javah org.coolreader.crengine.Engine
javah org.coolreader.crengine.DocView
